version: "3.8"

services:
  php:
    build: ./docker/php-fpm
    container_name: targee-php-fpm
    image: targee/php-fpm
    volumes:
      - ${PATH_HOST}:${PATH_CONTAINER}
      - ${PATH_SERVICE}/logs/xdebug:/var/log/xdebug
    working_dir: ${PATH_CONTAINER}
    environment:
      XDEBUG_CONFIG: "client_host=192.168.222.1 start_with_request=no client_port=9008"
      XDEBUG_SESSION: "PHPVCS"
      PHP_IDE_CONFIG: "serverName=school-server"
    ports:
      - "9010:9000"
    networks:
      - targee_net

  nginx:
    build:
      context: docker/nginx
    image: targee/http-nginx
    container_name: targee-http-nginx
    depends_on:
      - php
    volumes:
      - ${PATH_HOST}:${PATH_CONTAINER}
      - ${PATH_SERVICE}/logs/nginx:/var/log/nginx
    ports:
      - "192.168.222.1:80:80"
      - "192.168.222.1:443:443"
    networks:
      - targee_net

#  mysql:
#    build:
#      context: docker/mysql
#    image: targee/mysql-db
#    container_name: targee-mysql-db
#    command: --default-authentication-plugin=mysql_native_password
#    user: '1000'
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: qwertynet
#      MYSQL_DATABASE: ${MYSQL_DB}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASS}
#    volumes:
#      - ${DB_PATH_HOST}:/var/lib/mysql
#    ports:
#      - "33060:3306"
#    depends_on:
#      - php-apache
#    networks:
#      - targee_net
###     targee_net:
###       ipv4_address: 192.168.222.4

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: targee-dev-pma
#    restart: always
#    depends_on:
#      - mysql
#    ports:
#      - "8080:80"
#    environment:
#      PMA_ARBITRARY: 1
#      PMA_HOST: ${MYSQL_HOST}
#      PMA_USER: ${MYSQL_USER}
#      PMA_PASSWORD: ${MYSQL_PASS}
#    volumes:
#      - /session
#    networks:
#      - targee_net

networks:
  targee_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.222.0/28 # нам много адресов не нужно
